### Listar todas as tasks
GET https://tasks-api-ralh.onrender.com/tasks

### Criar nova task
POST https://tasks-api-ralh.onrender.com/tasks
Content-Type: application/json

{
  "title": "Minha nova task 3 teste"
}

### Deletar task por ID
DELETE https://tasks-api-ralh.onrender.com/tasks/1
