{
 "title": "Tasks API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total de Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memória Heap (Node.js)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "Heap" }
   ]
  },
  {
   "title": "Taxa de Requests por Rota (req/s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m])) by (method, route)",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Latência P95 (segundos)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, route))",
     "legendFormat": "p95 {{route}}"
    }
   ]
  }
 ]
}